In [10]:
import numpy as np

l1 = [1,2,34,5,6]

print(np.array(l1))

l2 = [33,44,55,66]

l3 = l1+l2

arr = np.array(l3)
print(arr)
print(arr.shape)
print(arr.dtype) 


[ 1  2 34  5  6]
[ 1  2 34  5  6 33 44 55 66]
(9,)
int32


In [16]:
import numpy as np
arr = np.zeros(5)
print(arr)
print(arr.dtype)

[0. 0. 0. 0. 0.]
float64


In [23]:
import numpy as np
arr = np.ones(5)
print(arr)
print(arr.dtype)

arr2 = np.ones([5,5])
print(arr2)

emptyarr = np.empty(5)
print(emptyarr)

[1. 1. 1. 1. 1.]
float64
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1.]


In [24]:
import numpy as np
arr = np.arange(5)
print(arr)
print(arr.dtype)

arr2 = np.arange(5,50,2)
print(arr2)

[0 1 2 3 4]
int32
[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


In [3]:
lis = ['a','b','c','d']
l = lis[::-1]
l

['d', 'c', 'b', 'a']