In [4]:
import numpy as np

In [5]:
from __future__ import division

In [6]:
5/2

2.5

In [9]:
arr = np.array([[1,2,3,4,5],[9,10,11,12,13]])

In [10]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 9, 10, 11, 12, 13]])

In [11]:
arr*arr #Multipyng elements of the array with itself

array([[  1,   4,   9,  16,  25],
       [ 81, 100, 121, 144, 169]])

In [13]:
arr-arr #Substracting elements of the array with itself

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
1/arr #Dividing elements of the array with 1

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308]])

In [17]:
arr**3 #Array elements to the power of 3

array([[   1,    8,   27,   64,  125],
       [ 729, 1000, 1331, 1728, 2197]], dtype=int32)