In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[1]

1

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[0:5] = 100 #All the values starting from index 0 till 4 are set to 100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_arr = arr[0:6] #Slice does not copy array elements, its just a view of the original array ... so as to use memory efficiently
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:] = 99 
print(slice_of_arr)
print(arr) #Values are also changed in the original array

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


In [17]:
arr_copy = arr.copy() #To avoid changes me made to the original array, use the copy method
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
arr_2d[1]

array([20, 25, 30])